services:
  apache:
    build: ./docker/apache
    container_name: lamp-php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: lamp-mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: lamp
      MYSQL_DATABASE: lamp
      MYSQL_USER: lamp
      MYSQL_PASSWORD: lamp
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: lamp
    ports:
      - 8001:80
    depends_on:
      - mysql